/*
* generated by Xtext
*/
package org.eclipse.ease.ui.expression.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.ease.ui.expression.xtext.services.CoreExpressionGrammarAccess;

public class CoreExpressionParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CoreExpressionGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.ease.ui.expression.xtext.parser.antlr.internal.InternalCoreExpressionParser createParser(XtextTokenStream stream) {
		return new org.eclipse.ease.ui.expression.xtext.parser.antlr.internal.InternalCoreExpressionParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}
	
	public CoreExpressionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CoreExpressionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
